spring:
  datasource:
    name: testDataPrediction
    url: jdbc:mysql://94.191.122.68:3306/testDataPrediction
    username: root
    password: root

server:
  port: 10002


## Undertow 日志存放目录
#server:
#  undertow:
#    accesslog.dir: /root
#  accesslog:
#    enabled: false # 是否启动日志
#    pattern: common # 日志格式
#    prefix: access_log # 日志文件名前缀
#    suffix: log    # 日志文件名后缀
#  max-http-post-size: 0    # HTTP POST请求最大的大小
#  io-threads: 4  # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
#  worker-threads: 20  # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
#  buffer-size: 1024  # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理  每块buffer的空间大小,越小的空间被利用越充分
#  buffers-per-region: 1024  # 每个区分配的buffer数量 , 所以pool的大小是buffer-size * buffers-per-region
#  direct-buffers: true  # 是否分配的直接内存


